var BOOT = [
    {o: 'info', m: 'initiating boot sequence..'},
    {o: 'info', m: 'version [0.0.1] -- unstable.'},
    {o: 'info', m: 'checking file systems.. fsck from util-linux 2.20.1'},
    {o: 'info', m: '...done.'},
    {o: 'info', m: 'mounting local filesysyems:'},
    {o: 'info', m: '...done.'},
    {o: 'info', m: 'setting kernel variables:'},
    {o: 'info', m: '... done.'},
    {o: 'info', m: 'configuring network interfaces:'},
    {o: 'info', m: '...done'},
    {o: 'info', m: 'starting daemons:'},
    {o: 'info', m: '...done'},
    {o: 'info', m: 'starting secure shell server:'},
    {o: 'info', m: '...done'},
    {o: 'info', m: '...'},
    {o: 'info', m: '_'},
    {o: 'info', m: '_'},
    {o: 'info', m: '_'},
    {o: 'info', m: '_'},
    {o: 'info', m: '_'},
    {o: 'info', m: '_'},
    {o: 'info', m: '_'},
    {o: 'info', m: '_'},
    {o: 'info', m: '_'},
    {o: 'info', m: 'login: root'},
    {o: 'info', m: 'password: *********'},
    {o: 'info', m: '\n'},
    {o: 'info', m: '_'},
    {o: 'info', m: '_'},
    {o: 'info', m: '_'},
    {o: 'info', m: '_'},
    {o: 'info', m: '_'},
    {o: 'info', m: '_'},
    {o: 'info', m: '_'},
    {o: 'info', m: '_'},
];

var INTRO = [
    {o: 'mirror', m: 'Good Evening, user_42@m1rr0r..'},
    {o: 'mirror', m: 'The company needs you to fight an intruder.'},
    {o: 'mirror', m: 'Our fear is that one employee is having mental illness,'},
    {o: 'mirror', m: 'and he\'s now attempting to destroy the company.'}
]
